### ISSUE TITLE
When showing categorical tesselation, tesselate the whole bar

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/data-hunch#1]
These patches look a bit odd: 

<img width="72" alt="image" src="https://user-images.githubusercontent.com/2039375/157078323-a0b8ae78-7761-4255-a628-aa60f5ff17d1.png">

Maybe we can try to show the whole bar tessellated?

We could keep the tessellated area slightly smaller then the bar, so it's obvious what the original color was.

**Comment by haihan-lin** [comment]
updated. 
![image](https://user-images.githubusercontent.com/14115944/157141391-36566e61-8868-40f1-9b59-d1737c957cd1.png)

**Comment by alexsb** [comment]
This looks better. Can you try a narrower stroke (2px instead of 4), but opaque?

**Comment by haihan-lin** [comment]
![image](https://user-images.githubusercontent.com/14115944/157726542-1c14cc03-9501-4c28-8722-d272b524e313.png)

**Comment by alexsb** [comment]
Make each edge of the triangle roughly equally long

**Comment by haihan-lin** [comment]
![WeChat459df906bc646ae23b9516226f431f27](https://user-images.githubusercontent.com/14115944/157738538-7e8c0c5d-9a1e-4d00-b7d1-a887caa9ce3a.png)

**Comment by alexsb** [comment]
Next stop sketchiness :)

**Comment by haihan-lin** [comment]
![WeChat235dedc4eef1b2f1cb601ff0e76bbc3b](https://user-images.githubusercontent.com/14115944/157753476-562ed421-d1ae-4f89-9ca8-4a9cd7a8553d.png)

Used solid for fill because other styles make it a bit harder to see. 

https://github.com/rough-stuff/rough/wiki

Here is the documentation for RoughJS, and it shows all the style for fill.
